# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- backup.appuio.ch_schedules.yaml
- backup.appuio.ch_backups.yaml
- backup.appuio.ch_restores.yaml
- backup.appuio.ch_archives.yaml
- backup.appuio.ch_checks.yaml
- backup.appuio.ch_prunes.yaml
- backup.appuio.ch_snapshots.yaml
- backup.appuio.ch_prebackuppods.yaml
- backup.appuio.ch_effectiveschedules.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
